export const FETCH_PHOTOS_ERROR = "FETCH_PHOTOS_ERROR";
export const FETCH_PHOTOS_PENDING = "FETCH_PHOTOS_PENDING";
export const FETCH_PHOTOS_SUCCESS = "FETCH_PHOTOS_SUCCESS";

export const SET_PAGE = "SET_PAGE";
export const SET_FILTERS = "SET_FILTER";
export const CLEAR_PHOTOS = "CLEAR_PHOTOS";
